# Generated by Django 3.0.6 on 2020-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200630_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prefered_branch',
            field=models.CharField(blank=True, default='CSE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='puc_college',
            field=models.CharField(blank=True, default='MITM', max_length=200, null=True),
        ),
    ]
