# Generated by Django 3.0.6 on 2020-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200630_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prefered_branch',
            new_name='preffered_branch',
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
