# Generated by Django 3.0.6 on 2020-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
