# Generated by Django 3.0.6 on 2020-07-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_has_multiple_answers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='options',
            unique_together=set(),
        ),
    ]
