# Generated by Django 3.0.6 on 2020-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200702_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(max_length=500),
        ),
    ]
